//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingId { get; set; }
        public int RatingNumber { get; set; }
        public string RatingImg { get; set; }
        public System.DateTime RatingDate { get; set; }
        public string RatingDescription { get; set; }
        public int AirlineId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual User User { get; set; }
    }
}
